server:
  port: 10001

spring:
  application:
    name: user-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
