server:
  port: 10002

spring:
  application:
    name: post-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka